#import "../../utils.typ": *

== Algebraic Integers and Burnside's $p^alpha q^beta$ Theorem

#definition(title: [Algebraic Number and Algebraic Integer])[
  Let $z in CC$.
  #enum(
    enum.item[
      We say that $z$ is an #highlightIndex[algebraic number]
      if $z$ is the root of a polynomial
      with rational coefficients.
    ],
    enum.item[
      We say that $z$ is an #highlightIndex[algebraic integer]
      if $z$ is the root of a monic polynomial with
      integer coefficients.
    ],
    enum.item[
      The set of algebraic integers is denoted by $algebraicInteger$.
      #index(display: [$algebraicInteger$], "AA")
    ],
  )
]

#lemma[
  #enum(
    enum.item[
      Every integer is an algebraic integer.
    ],
    enum.item[
      Every root of unity is an alegbraic integer.
    ],
    enum.item[
      If $z$ is an alegbraic integer,
      then $m z$ is an algebraic integer for all $m in ZZ$.
    ],
    enum.item[
      A rational number is an alegbraic integer
      if and only if it is an integer.
    ],
  )
]

#proposition[
  Let $M$ be a finitely generated subgroup of $(CC, +)$.
  Then
  $
    {z in CC | z M subset.eq M} subset.eq algebraicInteger.
  $
]
#proof[
  Let ${m_1,...,m_n}$ be a set of generator of $M$.
  Since $z M subset.eq M$,
  for each $i in {1,...,n}$,
  we have $z m_i = z_(i,1) m_1 + ... + z_(i,n) m_n$
  with $z_(i, j) in ZZ$.
  Then we have
  $
    mat(
      z_(1,1), dots, z_(1,n);
      dots.v, dots.down, dots.v;
      z_(n,1), dots, z_(n,n);
    )
    mat(
      m_1;
      dots.v;
      m_n;
    )
    = z mat(
      m_1;
      dots.v;
      m_n;
    )
  $

  And thus, $z$ is a eigenvalue of the matrix with integer coefficients.
  And it is well-known that eigenvalue of matrix is given by a polynomial.
]

#theorem[
  Algebraic integers form a subring of $CC$.
]
#proof[
  Given $a,b in algebraicInteger$,
  we have two monic polynomial with integer coefficients,
  s.t. $a,b$ is the root of them resp.
  $
    a^n + a_(n-1) a^(n-1) + ... + a_0 = 0,
    b^m + b_(m-1) b^(m-1) + ... + b_0 = 0
  $
  Let $M$ be the subgroup of $(C, +)$
  generated by ${a^i b^j | i in {0,...,n-1}, j in {0,...,m-1}}$.

  We assert that $(a+b) M subset.eq M$.
  We only need to prove this for the generator of $M$.
  For $a^i b^j, i in {0,...,n}, j in {0,...,m}$.
  $(a+b)(a^i b^j) = a^(i+1) b^j + a^i b^(j+1)$.
  We prove that $a^(i+1) b^j in M$,
  and $a^i b^(j+1)$ will follows in a similar manner.

  If $i le n-2$, then $a^(i+1) b^j in M$.
  Otherwise $i = n-1$.
  Then
  $
    a^(i+1) b^j = a^n b^j = -(a_(n-1) a^(n-1) + ... + a_0) b^j in M
  $

  We have $a b M subset.eq M$ using similar idea.

  Thus $a + b, a b in algebraicInteger$,
  and we already know that $z a in algebraicInteger$, for all $z in ZZ$.
]

Next we return to representation theory and extract some algebraic integers from
the complex group ring of a finite group.

#lemma[
  Let $chi$ be a charactor of the finite group $G$.
  Then $chi (g)$ is an algebraic integer for all $g in G$.
]
#proof[
  Let $rho: G -> GL(V)$ be the representation.
  Then for each $g in G$,
  we have $g^n = 1$ for some $n$.
  And thus $rho(g)^n$ is the identity morphism.
  If $e$ is a eigenvalue of $rho(g)$ with eigenvector $v$.
  Then $g^n v = e^n v = id v = v$.
  Thus $e^n = 1$.
  And $e$ is an algebraic integer.
  Since the trace of $rho(g)$
  is the sum of all eigenvalue,
  it is a algebraic integer.
]

Recall the conjugacy class sums from @def:conjugacyClassSum.
#lemma[
  Let $G$ be a finite group
  and let $G_1, ..., G_r$ be the conjugacy classes in $G$.
  Let $S$ be the additive subgroup of $CC G$
  generated by the conjugacy class sums
  $hat(G_1),...hat(G_r)$.
  Then $S$ is a subring of $Z(CC G)$.
]

We will now conpute the value of the central characters
of simple $CC G$-moudles
on our conjugacy class sums.
These values turns out to be algebraic integers.
#theorem[
  Let $G$ be a finite group.
  Let $V$ be a simple $CC G$-module
  and let $g in G$.
  #enum(
    enum.item[
      The conjugacy class sum $hat(g^G)$
      acts on $V$ by the scalar $(abs(g^G)chi_V (g))/(chi_V (1)) in CC$:
      $
        hat(g^G) dot v = (abs(g^G)chi_V (g))/(chi_V (1)) dot v,
        forall v in V
      $
    ],
    enum.item[
      The scalar is an alegbraic integer.
    ],
  )
]
#corollary[
  Let $G$ be a finite group.
  Let $V$ be a simple $CC G$-module,
  then $dim V$ divides $abs(G)$.
]
