#import "../../../utils.typ": *

=== The Product Topology

#definition(title: [product topology])[
  Let $XX$ and $YY$ be topological spaces.  
  The #index(display: [product topology on $XX times YY$], [product topology on XX times YY]) #highlight[product topology] on $XX times YY$ has a basis $BB$ containing all sets of the form $U times V$,  
  where $U$ and $V$ are open sets of $XX$ and $YY$, respectively.
]<def:ProductTopology>

#theorem[
  #footnote[We omit the proof of this theorem as it is obvious.]
  If $BB$ and $CC$ are bases for the topologies of $XX$ and $YY$, respectively, then the collection
  $
  DD = { B times C | B in BB, C in CC }
  $
  is a basis for the topology of $XX times YY$.
]

#definition(title: [projection])[
  Let $pi_1: XX times YY -> XX$ be defined by  
  $
  pi_1(x,y) = x.
  $
  Let $pi_2: XX times YY -> YY$ be defined by  
  $
  pi_2(x,y) = y.
  $
  The maps $pi_1$ and $pi_2$ are called the #highlightIndex[projections] of $XX times YY$ onto its first and second factors, respectively.
]<def:Projection>

#theorem[
  #footnote[We omit the proof of this theorem as it is obvious.]
  The collection  
  $
  SS = { pi_1^(-1)(U) | U "open in" XX } union { pi_2^(-1)(V) | V "open in" YY }
  $
  is a subbasis for the product topology on $XX times YY$.
]

#definition(title: [box topology])[
  Let  
  $
  XX = XX_1 times XX_2 times ... times XX_n  "or"  XX_1 times XX_2 times ...
  $
  In the first (finite) case, all sets of the form  
  $
  U_1 times ... times U_n
  $
  where each $U_i$ is an open set of $XX_i$, form a basis.

  In the second (infinite) case, all sets of the form  
  $
  U_1 times U_2 times ...
  $
  where each $U_i$ is an open set of $XX_i$, also form a basis.

  The topology defined in this way is called the #highlightIndex[box topology].
]<def:BoxTopology>

#definition(title: [product topology (infinite)])[
  #footnote[In the finite case, the product topology and box topology coincide; they differ for an infinite cartesian product.]
  Let  
  $
  XX = XX_1 times XX_2 times ... times XX_n  "or"  XX_1 times XX_2 times ...
  $
  For each index $i$ let $pi_i$ denote the projection mapping  
  #footnote[This is also called a #highlightIndex[projection mapping] in a cartesian product.]  
  defined by  
  $
  pi_i: XX -> XX_i,
  $
  and for $x in XX$  
  $
  pi_i(x) = x_i.
  $

  All sets of the form $pi_i^(-1)(U_i)$, where $i$ is arbitrary and $U_i$ is open in $XX_i$, form a subbasis of $XX$.  
  The topology generated by this subbasis is called the #highlightIndex[product topology].  
  The space $XX$ with this topology is called a #highlightIndex[product space].
]<def:ProductTopologyInfinite>

#definition(title: [J-tuple])[
  Let $J$ be an index set #footnote[An index set might be ${1,...,n}$ or $ZZ_+$.]  
  Given a set $XX$, a #highlightIndex[J-tuple] is a function  
  $
  x: J -> XX.
  $
  If $alpha in J$, we write $x(alpha)$ as $x_alpha$, the $alpha$th #highlightIndex[coordinate] of $x$.  
  The function $x$ is often written as  
  $
  (x_alpha)_(alpha in J).
  $
  The set of all J-tuples of elements of $XX$ is denoted $XX^(J)$.
]<def:JTuple>

#definition(title: [cartesian product])[
  Let ${A_alpha}_(alpha in J)$ be an indexed family of sets; let $XX = union.big_(alpha in J) A_alpha$.  
  The #highlightIndex[cartesian product] of this family is denoted  
  $
  product_(alpha in J) A_alpha
  $
  and is defined to be the set of all J-tuples $(x_alpha)_(alpha in J)$ with $x_alpha in A_alpha$ for each $alpha in J$.  
  Equivalently, it is the set of all functions  
  $
  x: J -> union.big_(alpha in J) A_alpha
  $
  such that $x(alpha) in A_alpha$ for every $alpha in J$.
]<def:CartesianProduct>

#theorem(title: [Comparison of the box and product topologies])[
  #footnote[It is assumed the product topology is the default topology on $product XX_alpha$ unless stated otherwise.]
  The box topology on $product XX_alpha$ has as a basis all sets of the form $product U_alpha$ where each $U_alpha$ is "open in" $XX_alpha$.  
  The product topology on $product XX_alpha$ has as a basis all sets of the form $product U_alpha$ where each $U_alpha$ is "open in" $XX_alpha$ and $U_alpha = XX_alpha$ for all but finitely many indices $alpha$.
]

#theorem[
  #footnote[We omit the proof of this theorem as it is obvious.]
  Suppose each space $XX_alpha$ has a basis $BB_alpha$.  
  The collection of all sets  
  $
  product_(alpha in J) B_alpha
  $
  with $B_alpha in BB_alpha$ for every $alpha$ forms a basis for the box topology on $product_(alpha in J) XX_alpha$.

  The subcollection where $B_alpha in BB_alpha$ for only finitely many indices $alpha$ and $B_alpha = XX_alpha$ for all remaining indices forms a basis for the product topology on $product_(alpha in J) XX_alpha$.
]

#theorem[
  #footnote[We omit the proof of this theorem as it is obvious.]
  Let $A_alpha$ be a subspace of $XX_alpha$ for each $alpha in J$.  
  Then $product A_alpha$ is a subspace of $product XX_alpha$ (with the box topology) and also of $product XX_alpha$ (with the product topology).
]

#theorem[
  #footnote[We omit the proof of this theorem as it is obvious.]
  If each $XX_alpha$ is Hausdorff, then $product XX_alpha$ is Hausdorff in both the box and product topologies.
]

#theorem[
  Let ${XX_alpha}$ be an indexed family of spaces, and let $A_alpha subset.eq XX_alpha$ for each $alpha$.  
  If $product XX_alpha$ is given either the product or the box topology, then  
  $
  product overline(A_alpha) = overline(product A_alpha).
  $
]

#proof[
  Let $pi_alpha$ denote the projection mapping.  

  Let $x in product XX_alpha$, and let $V$ be an "open set in" $product XX_alpha$ containing $x$.

  If $x in product overline(A_alpha)$, then for each $alpha$ the set $pi_alpha(V)$ is "open in" $XX_alpha$ containing $x_alpha$, so $pi_alpha(V)$ intersects $A_alpha$.  
  Hence $V$ intersects $product A_alpha$, and therefore $x in overline(product A_alpha)$.

  Conversely, suppose $x in overline(product A_alpha)$.  
  Fix $alpha$. Let $U_alpha$ be an "open set of" $XX_alpha$ containing $x_alpha$.  
  Define $U_beta = XX_beta$ for $beta != alpha$, and set  
  $
  V = product_(beta in J) U_beta.
  $
  Then $V$ is an "open neighborhood of" $x$, so $V$ intersects $product A_alpha$.  
  That intersection implies $U_alpha$ intersects $A_alpha$, hence $x_alpha in overline(A_alpha)$.  
  Since this holds for each $alpha$, $x in product overline(A_alpha)$.
]

#theorem[
  Let $f: A -> product_(alpha in J) XX_alpha$ be given by  
  $
  f(a) = ( f_alpha(a) )_(alpha in J),
  $
  where each $f_alpha: A -> XX_alpha$.  
  If $product XX_alpha$ has the product topology, then $f$ is continuous iff each $f_alpha$ is continuous.
]

#proof[
  Let $pi_alpha$ be the projection mapping.

  For any $U$,  
  $
  f^(-1)(U) = inter.big_(alpha in J) f_alpha^(-1)( pi_alpha(U) ).
  $

  If each $f_alpha$ is continuous, then for any closed $V$ in $product XX_alpha$, each $pi_alpha(V)$ is closed in $XX_alpha$, and $f^(-1)(V)$ is an intersection of closed sets, hence closed; therefore $f$ is continuous.

  Conversely, suppose $f$ is continuous.  
  Fix $alpha$ and let $U_alpha$ be "open in" $XX_alpha$.  
  For $beta != alpha$ set $U_beta = XX_beta$ and put  
  $
  V = product_(beta in J) U_beta.
  $
  Then $V$ is "open in" $product XX_alpha$, and  
  $
  f^(-1)(V) = inter.big_(beta in J) f_beta^(-1)( pi_beta(V) ) = f_alpha^(-1)(U_alpha),
  $
  which is "open in" $A$. Thus $f_alpha$ is continuous.
]
