#import "../../../utils.typ": *

==== Exercise

#enum(
  enum.item[
    Show that if $AA$ is a basis for a topology on $XX$, then the topology generated by $AA$ equals the intersection of all topologies on $XX$ that contain $AA$.
    Prove the same if $AA$ is a subbasis.

    #proof[
      As a subbasis is also a basis, we directly prove the subbasis case.

      Let $SS = {TT_alpha}$ be the set containing all topologies $TT_alpha$ that contain $AA$.
      Let $TT$ be the topology generated by $AA$.
      Let $TT' = inter_(alpha) TT_alpha$. #footnote[It is obvious that $TT'$ is also a topology; we omit the proof here.]

      First, $AA subset.eq TT_alpha$ for each $alpha$.
      Hence by construction of the generated topology, $TT subset.eq TT_alpha$ for every $alpha$.
      Therefore $TT subset.eq TT'$.

      Conversely, since $AA subset.eq TT$, we have $TT in SS$.
      Thus $TT' = inter_(alpha) TT_alpha subset.eq TT$.

      Combining the two inclusions gives $TT = TT'$.
    ]
  ],
)
