#import "../../../utils.typ": *

=== Basis for a Topology

#definition(title: [basis])[
  If $XX$ is a set, a #highlightIndex[basis] for a topology on $XX$ is a collection $BB$ of subsets of $XX$ (called #highlightIndex[basis elements]) such that:

  + For each $x in XX$, there is at least one basis element $B in BB$ containing $x$.
  + If $x$ belongs to the intersection of two basis elements $B_1$ and $B_2$, then there is another element $B_3 in BB$ with $x in B_3$ and $B_3 subset.eq B_1 inter B_2$.
]<def:Basis>

#definition(title: [topology generated by basis])[
  Let $BB$ be a basis on $XX$. Let $UU$ be the collection of all subsets $U subset.eq XX$ such that for each element $x in U$ there is $B in BB$ with $x in B subset.eq U$.
  Then $UU$ is a topology on $XX$, called the #index(display: [topology $TT$ generated by $BB$], [topology TT generated by BB]) #highlight[topology $TT$ generated by $BB$].
]<def:TopologyGeneratedByBasis>

#lemma[
  Let $XX$ be a set and $BB$ a basis for a topology $TT$ on $XX$. Then $TT$ equals the set of all unions of elements of $BB$.
]<lem:BasisUnion>

#proof[
  Let $UU$ be the set of all unions of elements of $BB$.
  If $U in UU$, then $U$ is a union of basis elements, so for every $x in U$ there exists $B' in BB$ with $x in B' subset.eq U$. Hence $U in TT$.

  Conversely, if $U in TT$, then for each $x in U$ choose a basis element $B_x in BB$ with $x in B_x subset.eq U$. Then $U = union_(x in U) B_x$, so $U in UU$.

  Therefore $UU = TT$. #footnote[Note that this expression may not be unique.]
]<prf:BasisUnion>

#lemma[
  #footnote[We omit the proof of this lemma as it is obvious.]
  Let $XX$ be a topological space. Suppose $cal(C)$ is a collection of open sets of $XX$ such that for each open set $U$ of $XX$ and each $x in U$ there is $C in cal(C)$ with $x in C subset.eq U$. Then $cal(C)$ is a basis for the topology of $XX$.
]<lem:BasisCriterion>

#lemma[
  #footnote[We omit the proof of this lemma as it is obvious.]
  Let $BB$ and $BB'$ be bases for the topologies $TT$ and $TT'$ respectively on $XX$. The following are equivalent:

  + $TT'$ is finer than $TT$.
  + For each $x in XX$ and each basis element $B in BB$ containing $x$, there is a basis element $B' in BB'$ such that $x in B' subset.eq B$.
]<lem:FinerEquiv>

#definition(title: [standard topology on the real line])[
  Let $BB = {(a,b) | a<b, a in RR, b in RR}$. $BB$ forms a basis on the real line.
  The topology generated by $BB$ is called the #highlightIndex[standard topology on the real line].
  #footnote[Whenever we consider $RR$, we shall suppose it is given this topology unless we specifically state otherwise.]
]<def:StandardTopologyOnTheRealLine>

#definition(title: [lower limit topology on the real line])[
  Let $BB = {[a,b) | a<b, a in RR, b in RR}$. $BB$ forms a basis on the real line.
  The topology generated by $BB$ is called the #highlightIndex[lower limit topology on the real line].
  When $RR$ is given this topology, we denote it by $RR_l$.
]<def:LowerLimitTopologyOnTheRealLine>

#definition(title: [K-topology on the real line])[
  Let $BB = {(a,b) | a<b, a in RR, b in RR}$.
  Let $K = {x | x = 1/n, n in ZZ_+}$.
  Then $BB union {B without K | B in BB}$ forms a basis on the real line.
  The topology generated by $BB$ is called the #highlightIndex[K-topology on the real line].
  When $RR$ is given this topology, we denote it by $RR_K$.
]<def:KTopologyOnTheRealLine>

#lemma[
  #footnote[We omit the proof of this lemma as it is obvious.]
  The topologies $RR_l$ and $RR_K$ are strictly finer than the standard topology on $RR$.
]<lem:StrictlyFiner>

#lemma[
  The topologies $RR_l$ and $RR_K$ are not comparable.
]<lem:NotComparable>

#proof[
  Let $TT_l$ and $TT_K$ be the topologies of $RR_l$ and $RR_K$, respectively.
  Let $K = {x | x = 1/n, n in ZZ_+}$.

  First, we show $TT_l$ is not finer than $TT_K$.
  Consider $U = (-1,1) without K$ and the point $x = 0$.
  If there existed a lower-limit basis interval $B = [a,b) in TT_l$ with $0 in B subset.eq U$, then $0<b<=1$, so choose $n$ with $0<1/n<b$.
  Then $1/n in B$ but $1/n in.not U$, a contradiction. Hence no such $B$ exists.

  Next, we show $TT_K$ is not finer than $TT_l$.
  Let $U' = [a',b')$.
  Any basic $TT_K$-neighborhood of $a'$ is either an open interval $(a'',b'')$ or $(a'',b'') without K$ with $a''<a'<b''$.
  In either case, one can find $x$ such that $x in B'$ but $x in.not U'$, so no $TT_K$-basic set is necessarily contained in $U'$.

  Therefore, $TT_l$ and $TT_K$ are not comparable.
]<prf:NotComparable>

#definition(title: [subbasis])[
  A #highlightIndex[subbasis] $SS$ for a topology on $XX$ is a collection of subsets of $XX$ whose union equals $XX$.
  The #highlightIndex[topology generated by the subbasis] $TT$ is the collection of all unions of finite intersections of elements of $SS$.
  #footnote[It is obvious that $TT$ is a topology; we omit the proof here.]
]<def:Subbasis>
