#import "../../utils.typ": *

== Induced Representations

#definition(title: [Induced $k G$-module $inducedKGModule(H, G, W)$])[
  Let $G$ be a finite group,
  and $H$ be a subgroup
  of $G$.
  Then the #highlight[induced $k G$-module $inducedKGModule(H, G, W)$]
  #index(
    display: [Induced $k G$-module $inducedKGModule(H, G, W)$],
    [induced k G-module Ind^G_H W],
  )
  #index(
    display: [$inducedKGModule(H, G, W)$],
    [Ind^G_H W],
  )
  is the $k G$-module:
  $
    inducedKGModule(H, G, W) = k G tensor_(k H) W.
  $

  If $sigma: H -> GL(H)$
  is the representation of $H$ afforded by $W$,
  then we call the representation of $G$ afforded by
  $inducedKGModule(H, G, W)$
  the #highlightIndex[induced representation]
  and denote it by $inducedKGModule(G, H, sigma)$.
]

#proposition[
  Let ${x_1,...,x_m}$ ve a complete set of left coset
  representatives for $H$ in $G$
  sot that $G = x_1 H union ... union x_m H$.
  Then there is a vector space decomposition
  $
    inducedKGModule(H, G, W) =
    (x_1 tensor_(k H) W) directSum ... directSum (x_m tensor_(k H) W).
  $
  And we have
  $
    dim inducedKGModule(H, G, W) = |G : H| dim W.
  $
] <prop:decompositionOfInducedKGModule>
#remark[
  Note that $inducedKGModule(H, G, W)$ is a $k$ vector space,
  and $x_i tensor_(k H) W$
  should be understand as the $k$ vector subspace
  of $inducedKGModule(H, G, W)$
  generated by ${x_i tensor_(k H) w | w in W}$.
]
#proof[
  Just unwrap the def.
]

#definition(title: [$restrictionKGModule(H, G, V)$])[
  Let $G$ be a finite group,
  let $V$ be a subgroup
  of $G$
  and let $V$ be a $k G$-module.
  Then $V$ is also a $k H$-module
  by restricting the action of $k G$
  to its subring $k H$.
  We denote the resulting $k H$-module
  $restrictionKGModule(H, G, V)$.
  #index(
    display: [$restrictionKGModule(H,G,V)$],
    [Res_H^G V],
  )
]

#proposition[
  Let $G$ be a finite group,
  let $V$ be a subgroup
  of $G$.
  Let $W$ be a $k H$-module,
  and let $V$ be a $k G$-module.
  Then, we have natural iso:
  $
    Hom_(k G) (inducedKGModule(H, G, W), V)
    iso Hom_(k H) (W, restrictionKGModule(H, G, V)).
  $
]
#proof[
  This basically says the functor
  $inducedKGModule(H, G, square): ""_(k H) Mod -> ""_(k G)Mod$
  is a left adjoin of the functor
  $restrictionKGModule(H, G, square): ""_(k G)Mod -> ""_(k H) Mod$.

  And if we consider $k G$ as a $k G - k H$ bimodule,
  then we have:
  $
    Hom_(k G) (k G tensor_(k H) W, V)
    iso Hom_(k H) (W, Hom_(k G)(k G, V)).
  $

  And if $k G$ is $k G - k H$ bimodule,
  then $Hom_(k G)(k G, V)$
  is naturally iso to the left $k H$ module,
  $V$,
  which is $restrictionKGModule(H, G, V)$ by definition.
]

#definition(title: [Induced and Restricted Charactor])[
  Let $H$ be a subgroup of the finite group G.
  #enum(
    enum.item[
      Let $phi$ be a charactor of $H$
      afforded by the $CC H$-module $W$.
      Then the #highlightIndex[induced charactor]
      is the charactor $inducedKGModule(H, G, phi)$
      of the $CC G$-module $inducedKGModule(H, G, W)$.
    ],
    enum.item[
      Let $psi$ be a charactor of $H$
      afforded by the $CC G$-module $V$.
      Then the #highlightIndex[restricted charactor]
      is the charactor $restrictionKGModule(H, G, psi)$
      of the $CC H$-module $restrictionKGModule(H, G, V)$.
    ],
  )
]
#remark[
  We will now use a subscript to indicate
  which group we are using for the inner product
  of class functions, i.e.
  $
    innerProduct(square, square)_G: classFunctionSpace(G)times classFunctionSpace(G)
    -> CC
  $
]

#corollary(title: [Frobenius Reciprocity])[
  Let $phi$ be a charactor of $H$,
  and $psi$ be a charactor of $G$.
  Then
  $
    innerProduct(inducedKGModule(H, G, phi), psi)_G
    = innerProduct(phi, restrictionKGModule(H, G, psi))_H
  $
  #index[Frobenius Reciprocity]
]
#proof[
  Let $U$ be the $CC G$-module
  whose charactor is $psi$,
  and $W$ be the $CC H$-module
  whose charactor is $phi$.
  Then
  $innerProduct(inducedKGModule(H, G, phi), psi)_G
  = dim Hom_(CC G) (inducedKGModule(H, G, W), U)
  = dim Hom_(CC H) (W,restrictionKGModule(H, G, U))
  = innerProduct(phi, restrictionKGModule(H, G, psi))_H$.
]

Given $H$ a subgroup of the finite group $G$,
if $phi$ is a charactor of some $G$-representation,
and $psi = restrictionKGModule(H, G, phi)$
is the charactor of the restriction representation.
Then Since $psi(h)$
is the trace of the action of an element $h in H$
on $U$,
it is clear that $psi$
is simply the restriction of the class fucntion
$phi in classFunctionSpace(G)$ to $H$.
And we have a natural linear map
$
  restrictionKGModule(H, G, "") : classFunctionSpace(G) -> classFunctionSpace(H)
$

While we may wonder, if there is a corresponding lienar map
in the opposite direction
$
  inducedKGModule(H, G, ""): classFunctionSpace(H) -> classFunctionSpace(G)
$
And we will give a lemma,
about how to calculate $inducedKGModule(H, G, "")$.

#lemma[
  Let $H$ be a subgroup of the finite group $G$.
  Let ${x_1,...,x_m}$ be a complete set of left coset
  representatives for $H$
  in $G$ so that $G = x_1 H union ... union x_m H$.
  For each $g in G$,
  write
  $
    g x_i H = x_(g dot i H), forall i in {1, ..., m}
  $
  for some permuation $i mapsto g dot i$ of ${1,...,m}$.
  Define
  $
    "Fix"(g) = {i in {1,...,m} | g dot i = i}
  $
  to be the fixed-point set of $g$
  in its action on ${1,...,m}$.
  Then for every finite dimensional $CC H$-module $W$,
  we have
  #enum(
    enum.item[
      $x_(g dot i)^(-1) g x_i in H, forall i in {1,...,m}, g in G$.
    ],
    enum.item[
      $g (x_i tensor_(k H) W) subset.eq x_(g dot i) tensor_(k H) W$,
      where $x_i tensor_(k H) W$ is defined as in
      @prop:decompositionOfInducedKGModule.
    ],
    enum.item[
      $(inducedKGModule(H, G, chi_W))(g)
      = sum_(i in "Fix"(g)) chi_W (x_i^(-1) g x_i)$.
    ],
  )
]
#proof[
  #enum(
    enum.item[
      As $g x_i H = x_(g dot i) H$,
      we have $g x_i in x_(g dot i) H$,
      thus, exists $h in H$, s.t. $g x_i = x_(g dot i) h$,
      thus $x_(g dot i)^(-1) g x_i = h in H$.
    ],
    enum.item[
      For $w in W$,
      we have $g (x_i tensor_(k H) w) = (g x_i) tensor_(k H) w
      = (x_(g dot i) x_(g dot i)^(-1) g x_i) tensor_(k H) w
      = x_(g dot i) tensor_(k H) (x_(g dot i)^(-1) g x_i w) in x_(g dot i) tensor_(k H) W$.
    ],
    enum.item[
      Given $f in Hom_k (inducedKGModule(H, G, W),inducedKGModule(H, G, W))$,
      by the decompostion @prop:decompositionOfInducedKGModule,
      we can decompose $f$
      as the following matrix:
      $
        f = mat(
          f_(1,1), f_(1,2), dots, f_(1,m);
          f_(2,1), f_(2,2), dots, f_(2,m);
          dots.v, dots.v, dots.down, dots.v;
          f_(m,1), f_(m,2), dots, f_(m,m);
        )
      $
      where $f_(i,j) in Hom_k (x_i tensor_(k H) W, x_j tensor_(k H) W)$
      And
      $
        tr(f) = sum_(i in {1,...,M}) tr(f_(i,i))
      $

      If we are given $rho: G -> inducedKGModule(H, G, W)$
      the induced representation,
      then for $g in G$,
      $rho(g) in Hom_k (inducedKGModule(H, G, W),inducedKGModule(H, G, W))$,
      and the $i,i$th decomposition $rho(g)_(i,i) neq 0$,
      iff $i in "Fix"(g)$ by last item.
      Again, by last item,
      the action $g$ on $x_i tensor_(k H) W$
      is exactly $x^(-1) g x_i$ on $W$, since $x_i tensor_(k H) W iso W$.
      Thus $tr(rho(g)_(i,i)) = chi_W (x^(-1) g x_i)$.
      And we have the desired result.
    ],
  )
]

It turns out that there is a more invariant way of expressing the result of this
calculation, which does not depend on the choice of coset representatives.

#definition(title: [Extension by Zero])[
  Let $H$ be a subgroup of the finite group $G$.
  For each $phi: H -> CC$, define its #highlightIndex[extension by zero]
  to $G$ to be the
  function $exntensionByZero(phi): G -> CC$
  which agrees with $phi$ on $H$ and which is zero on $G setminus H$.
]
#theorem[
  Let $H$ be a subgroup of the finite group $G$.
  And let $W$ be a finite dimensional $CC H$-module.
  Then for all $g in G$
  we have
  $
    (inducedKGModule(H, G, chi_W))(g) = 1/abs(H) sum_(x in G)
    exntensionByZero(chi_W) (x^(-1)g x).
  $
]
#proof[
  Just use the last lemma,
  and unwrap the definition.
]
#remark[
  If $g in G$, s.t. $g^G inter H = emptyset$,
  then the last theorem tells us $(inducedKGModule(H, G, chi_W))(g)= 0$.
]

#corollary[
  let $H$ be a subgroup of $G$.
  Define
  $
    & inducedKGModule(H, G, "")  & : & classFunctionSpace(H) -> classFunctionSpace(G) \
    & inducedKGModule(H, G, phi) & : & g mapsto 1/abs(H) sum_(x in G) exntensionByZero(chi_W) (x^(-1)g x),
                                       forall phi in classFunctionSpace(H), g in G
  $

  Then $inducedKGModule(H, G, "") : classFunctionSpace(H) -> classFunctionSpace(G)$
  is left adjoint to
  $restrictionKGModule(H, G, "") : classFunctionSpace(G) -> classFunctionSpace(H)$:
  $
    innerProduct(inducedKGModule(H, G, phi), psi)
    = innerProduct(phi, restrictionKGModule(H, G, psi)),
    forall phi in classFunctionSpace(H), psi in classFunctionSpace(G)
  $
]

There is another formulation
of the last corollary:
#corollary[
  Let $H$ be a subgroup of $G$. Let
  $g in G$, and let
  ${h_1, · · · , h_l}$ be a
  complete set of representatives for the conjugacy classes in $H$ contained in $g G inter H$:
  $
    g^G inter H = h_1^H union ... union h_l^H.
  $
  Then for every finite dimensional $CC H$-module $W$,
  $
    chi_(inducedKGModule(H,G,W))(g)
    = abs(G)/abs(H) sum_(i=1)^l abs(h_i^H)/abs(g^G) chi_W (h_i).
  $
]

Next, we specialise to the case where we have a normal subgroup $N$ of $G$.

#definition(title: [$x$-twist])[
  Let $N$ be a normal subgroup of a finite group $G$,
  let $x in G$
  and let $phi: N -> CC$.
  The #highlight[$x$-twist]
  #index(display: [$x$-twist], [x-twist])
  of $phi$
  is the function:
  $
    phi^x: N -> CC, h mapsto phi(x^(-1) h x).
  $

  Since $N$ is normal,
  if $h in classFunctionSpace(N)$,
  then $phi^x in classFunctionSpace(N)$.

  Also when $h in classFunctionSpace(N)$,
  if $x_1 N = x_2 N, x_1, x_2 in G$,
  then it is easy to check that $phi^(x_1) = phi^(x_2)$.
  Then $phi^x$ only depends $x N in G \/ N$,
  and this defines a $G \/ N$ action on $classFunctionSpace(H)$:
  $
    x N dot phi = phi^x, forall x H in G \/ N, phi in classFunctionSpace(N).
  $
]

#proposition[
  Let $N$ be a normal subgroup of $G$.
  Let $phi$ be a charactor of $N$.
  Then
  #enum(
    enum.item[
      $phi^x$ is another charactor of $N$.
    ],
    enum.item[
      $restrictionKGModule(N,G, inducedKGModule(N,G,phi))
      = phi^(x_1) + ... + phi^(x_m)$,
      where ${x_1, ..., x_m}$
      is a complete set of left coset
      representatives for $N$ in $G$.
    ],
  )
]
#proof[
  Just calculations.
]

#corollary[
  Let $N$ be a normal subgroup of $G$.
  Let $phi$ be an irreducible charactor of $N$,
  s.t. $phi^x neq phi$
  for all $x in G setminus N$.
  Then the charactor $inducedKGModule(H,G,phi)$ is irreducible.
]