#import "../../utils.typ": *

== Representations of Finite Groups

#definition(title: "General Linear Group")[
  Let $V$ be an $n$-dimensional vector space over a field $k$.
  A #highlightIndex("general linear group") $G L(V)$ is the group of
  invertible linear transformations from $V$ to itself under composition.
]

#definition(title: "representation of group")[
  A #highlightIndex("representation") of a finite group $G$ over a field $k$
  is a group homomorphism
  $
    rho: G to G L(V)
  $
  for some vector space $V$ over $k$ with $dim V = n$.
  The integer $n$ is called the #highlightIndex("degree") of the representation.

  Alternatively, $rho: * \/ G to catFiniteDimVectorSpace(k)$
  is a functor from the one-object category associated to $G$
  to the category of finite-dimensional vector spaces over $k$.
]

#definition(title: "Free Vector Space")[
  Let $X$ be a set and $k$ be a field.
  The #highlightIndex("free vector space") $k X$ over $k$ generated by $X$
  is the vector space $V$ over $k$ consisting of all functions
  $
    f: X to k
  $
  such that $f(x) neq 0$ for only finitely many $x in X$.
  The addition and scalar multiplication are defined pointwise.
]

Note that $X$ is a basis of the free vector space $k X$.

#definition(title: "Permutation Representation")[
  Let $G$ be a finite group acting on a finite set $X$.
  The #highlightIndex("permutation representation") of $G$ over $k$
  associated to the action of $G$ on $X$ is the representation
  $
    rho: G to G L(k X)
  $
  defined as follows:
  For each $g in G$, the linear transformation $rho(g)$
  permutes the basis elements of the free vector space $k X$
  according to the action of $g$ on $X$.
]

#definition(title: "Faithful Representation")[
  A representation $rho: G to G L(V)$ is called #highlightIndex("faithful")
  if $rho$ is injective.
]

#definition(title: "Homomorphism of Representations")[
  Let $rho: G to G L(V)$ and $rho': G to G L(W)$
  be two representations of a finite group $G$ over a field $k$.
  A #highlightIndex("homomorphism of representations")
  from $rho$ to $rho'$ is a linear transformation
  $
    T: V to W
  $
  such that for all $g in G$, the following diagram commutes:
  #align(center, commutative-diagram(
    node((0, 0), [$k^n$]),
    node((0, 1), [$k^n$]),
    node((1, 1), [$k^m$]),
    node((1, 0), [$k^m$]),
    arr((0, 0), (0, 1), [$rho(g)$]),
    arr((0, 1), (1, 1), [$T$]),
    arr((0, 0), (1, 0), [$T$]),
    arr((1, 0), (1, 1), [$rho'(g)$]),
  ))

  We say that $rho$ and $rho'$ are #highlightIndex("isomorphic") or #highlightIndex("equivalent")
  if $T$ is an isomorphism.

  Alternatively, a homomorphism of representations
  is a natural transformation between the corresponding functors.
  And the isomorphism of representations
  is a natural isomorphism between the corresponding functors.
]

#definition(title: "G-stable Subspace")[
  Let $rho: G to G L(V)$ be a representation of a finite group $G$ over a field $k$.
  A subspace $W subseteq V$ is called #highlightIndex("G-stable")
  if for all $g in G$ and $w in W$, we have $rho(g)(w) in W$.
]

#definition(title: "Subrepresentation")[
  Let $rho: G to G L(V)$ be a representation of a finite group $G$ over a field $k$.
  A #highlightIndex("subrepresentation") of $rho$ is a representation
  $
    rho|_W: G to G L(W)
  $
  where $W$ is a $G$-stable subspace of $V$
  and for all $g in G$, $rho|_W (g)$ is the restriction of $rho(g)$ to $W$.
]

Note that there is a natural inclusion homomorphism
from the subrepresentation $rho|_W$ to the representation $rho$.

#definition(title: "Quotient Representation")[
  Let $rho: G to G L(V)$ be a representation of a finite group $G$ over a field $k$.
  Let $W$ be a $G$-stable subspace of $V$.
  The #highlightIndex("quotient representation") of $rho$ on $V \/ W$ is the representation
  $
    rho | _(V \/ W): G to G L(V \/ W)
  $
  defined as follows:
  For all $g in G$ and $v + W in V \/ W$, we have
  $
    rho | _(V \/ W)(g)(v + W) = rho(g)(v) + W
  $.
]

Note that there is a natural projection homomorphism
from the representation $rho$ to the quotient representation $rho | _(V \/ W)$.

#lemma[
  Let $rho: G -> GL(V)$ and $rho': G -> GL(W)$ be two representations of a finite group $G$ over a field $k$.
  And $phi: V -> W$ be a homomorphism of representations.
  Then:
  + $ker phi$ is a $G$-stable subspace of $V$.
  + $Img phi$ is a $G$-stable subspace of $W$.
  + There is an induced isomorphism of representations
    $
      overline(phi): rho | _(V \/ ker phi) to rho' | _(Img phi)
    $.
]

#definition(title: "Trivial Representation")[
  Let $G$ be a finite group and $V$ be a vector space over a field $k$.
  The #highlightIndex("trivial representation") of $G$ over $k$ is the representation
  $
    bb(1): G to G L(V)
  $
  defined by $bb(1)(g) = 1$ for all $g in G$.
]

#definition(title: "Irreducible Representation")[
  A representation $rho: G to G L(V)$ of a finite group $G$ over a field $k$
  is called #highlightIndex("irreducible") or #highlightIndex("simple")
  if 
  + $V neq 0$
  + the only $G$-stable subspaces of $V$ are $0$ and $V$ itself.
]

#definition(title: "G-stable Complement Space")[
  Let $rho: G to G L(V)$ be a representation of a finite group $G$ over a field $k$.
  A subspace $U subseteq V$ is called a #highlightIndex("G-stable complement")
  of a $G$-stable subspace $W subseteq V$
  if $V = W directSum U$ and $U$ is $G$-stable.
]

#theorem(title: "Maschke")[
  #index("Maschke's Theorem")
  Let $rho: G -> GL(V)$ be a representation of a finite group $G$ over a field $k$.
  If the characteristic of $k$ does not divide the order of $G$,
  then for every $G$-stable subspace $W subseteq V$,
  there exists a $G$-stable complement $U subseteq V$ of $W$.
]

#proof[
  Since $W subseteq V$, there exists some projection $pi: V to W$
  s.t. $pi(w) = w, forall w in W$.
  We define a new linear transformation
  $ phi: V to W$
  by:
  $
    phi(v) = 1/(|G|) sum_(g in G) rho(g)^(-1)(pi(rho(g)(v)))
  $

  And we verify that $phi$ is a projection onto $W$.
  For all $w in W$, we have:
  $
    phi(w) = 1/(|G|) sum_(g in G) rho(g)^(-1)(pi(rho(g)(w))) =
    1/(|G|) sum_(g in G) rho(g)^(-1)(rho(g)(w))  = w
  $
  And for all $v in V$,
  $
    phi(v) = 1/(|G|) sum_(g in G) rho(g)^(-1)(pi(rho(g)(v))) in W
  $

  And next we verify that $phi$ is a homomorphism of representations.
  For all $h in G$ and $v in V$, we have:
  $
    phi(rho(h)(v)) &= 1/(|G|) sum_(g in G) rho(g)^(-1)(pi(rho(g)(rho(h)(v)))) \
    &= 1/(|G|) sum_(g in G) rho(g)^(-1)(pi(rho(g h)(v)))
  $
  And
  $
    rho(h)(phi(v)) &= rho(h)(1/(|G|) sum_(g in G) rho(g)^(-1)(pi(rho(g)(v)))) \
    &= 1/(|G|) sum_(g^(-1) in G) rho(h)(rho(g)(pi(rho(g)^(-1)(v)))) \
    &= 1/(|G|) sum_(g^(-1) in G) rho(h g)(pi(rho(g)^(-1)(v))) \
    &= 1/(|G|) sum_(h g in G) rho(g^(-1))(pi(rho(g h)(v))) \
    & = phi(rho(h)(v))
  $

  Thus, $phi$ is a homomorphism of representations.
  And by the previous lemma,
  $ker phi$ is a $G$-stable complement of $W$.
]

#definition(title: "Completely Reducible Representation")[
  A representation $rho: G to G L(V)$ of a finite group $G$ over a field $k$
  is called #highlightIndex("completely reducible")
  if there exists a collection of $G$-stable spaces ${U_1, dots, U_n}$ such that
  $V = directSum.B U_i$,
  and $rho|_(U_i)$ is irreducible for all $i$.
]

#corollary[
  Let $rho: G -> GL(V)$ be a representation of a finite group $G$ over a field $k$.
  If the characteristic of $k$ does not divide the order of $G$,
  then $rho$ is completely reducible.
]
#proof[
  This can be proved by a simple induction using Maschke's Theorem.
]