#import "../../../utils.typ": *

=== Localization

Localization of a ring could gives us some extra information
on the modules and rings.
A typical step would be first apply the Localization
for all the module and rings,
then study the property of the localized rings and modules,
and globalize the property.

==== Localization Steps

#definition(title: "multiplicative")[
  A subset $S subset.eq R$ of a commutative ring $R$
  is #highlightIndex("multiplicative")
  if and only $0 in.not S$, $1 in S$,
  and for all $s, s' in S$, $s s' in S$.
]

#example[
  If $cal(p)$ is a prime ideal in $R$,
  then $S = R - cal(p)$ is multiplicative in $R$.
]

#definition(title: [$k$-algebra])[
  Let $k$ be a commutative ring.
  Then a ring $R$ is a #index(display: [$k$-algebra], "k-algebra")
  #highlight[$k$-algebra]
  if $R$ is a $k$ module, satisfy:
  $
    a(r s) = (a r) s = r (a s)
  $
  for all $a in k$ and $r, s in R$.
]

#definition(title: "localization of ring")[
  If $S subset.eq R$ is multiplicative,
  then the #highlightIndex("localization") of $R$
  is a pair $(S^(-1)R, h)$ where $S^(-1)R$ is a commutative $R$-algebra,
  $h$ is a $R$-algebra map,
  and $h(s)$ is invertible for all $s in S$,
  s.t. it solves the following universal mapping problem:
  #align(center, commutative-diagram(
    node((0, 0), [$R$]),
    node((0, 2), [$S^(-1)R$]),
    node((1, 1), [$A$]),
    arr((0, 0), (1, 1), [$phi$], label-pos: right),
    arr((0, 0), (0, 2), [$h$]),
    arr((0, 2), (1, 1), [$tilde(phi)$], "dotted"),
  ))
  That is for all pairs $(A, phi)$,
  where $A$ is a commutative $R$-algebra,
  $phi$ is a $R$-algebra map,
  and $phi(s)$ is invertible for all $s in S$,
  there exists a unique $R$-algebra map $tilde(phi)$,
  that makes the diagram commute.
]

The localization is easily seen to be unique,
similar to other universal mapping problem.
#proposition[
  Given a multiplicative subet $S$ of a commutative ring $R$,
  the localization $(S^(-1)R, h)$ is unique up to isomorphism. 
]
#proof[
  If there is another localization $(A,h')$, then we have the follwing
  commutative diagrams:
  #align(center, commutative-diagram(
    node((1, 0), [$R$]),
    node((1, 1), [$A$]),
    node((0, 1), [$S^(-1)R$]),
    node((2, 1), [$S^(-1)R$]),
    node((1, 3), [$R$]),
    node((0, 4), [$A$]),
    node((2, 4), [$A$]),
    node((1, 4), [$S^(-1)R$]),
    arr((1, 0), (1, 1), [$h'$]),
    arr((1, 0), (0, 1), [$h$]),
    arr((1, 0), (2, 1), [$h$], label-pos: right),
    arr((0, 1), (2, 1), [$1$], curve: 30deg, label-pos: left),
    arr((0, 1), (1, 1), [$phi$], label-pos: right, "dotted"),
    arr((1, 1), (2, 1), [$phi'$], label-pos: right, "dotted"),
    arr((1, 3), (1, 4), [$h$]),
    arr((1, 3), (0, 4), [$h'$]),
    arr((1, 3), (2, 4), [$h'$], label-pos: right),
    arr((0, 4), (1, 4), [$phi'$], label-pos: right, "dotted"),
    arr((1, 4), (2, 4), [$phi$], label-pos: right, "dotted"),
    arr((0, 4), (2, 4), [$1$], curve: 30deg),
  ))
  where $1$ is the identity map,
  and $phi$, $phi'$ is the map that make the two diagrams
  commute, that derived from the definition of the localization.
  Then $phi circle.small phi' = 1$ and $phi' circle.small phi = 1$,
  and we can easily seen that $phi$ is a isomorphism.
]

We will prove that the localization exists by constructions:
#proposition[
  Given a multiplicative subet $S$ of a commutative ring $R$,
  the localization $(S^(-1)R, h)$ exists.
] <existence-of-localizarion-ring-map>
#proof[
  Take $X = \{x_s divides s in S\}$ is a set of variable.
  Take $P = R[X]$ be the polynomial ring.
  And $I$ be the ideal of $P$ generated by $\{ s x_s - 1 divides s in S \}$.
  Take $A = P \/ I$,
  and $h: R -> A$ defined as the composition of the injection $i: R -> P$,
  and the natural map $p: P -> P \/ A$, i.e. $h = p circle.small i$.
  We assert that $(A, h)$ is the localization of $R$.
  $A$ is easily a $R$-algebra,
  $h$ is easily a $R$-algebra map.
  $h(s)$ is invertible since $h(s) = i(s) + I = s + I$,
  and $(s + I)(x_s + I) = 1 + I$.
  Thus, $h(s)p(x_s) = 1$.

  Next, we prove the universal mapping property.
  Given $(B, phi)$,
  where $B$ is a commutative $R$-algebra,
  $phi$ is a $R$-algebra map,
  and $phi(s)$ is invertible for all $s in S$.

  #align(center, commutative-diagram(
    node((0, 0), [$R$]),
    node((0, 2), [$R[X]$]),
    node((1, 1), [$A$]),
    node((2, 1), [$B$]),
    arr((0, 0), (1, 1), [$h$]),
    arr((0, 0), (0, 2), [$i$]),
    arr((0, 2), (1, 1), [$p$], label-pos: right),
    arr((0, 0), (2, 1), [$phi$], label-pos: right),
    arr((0, 2), (2, 1), [$phi'$], "dotted"),
    arr((1, 1), (2, 1), [$phi''$], "dotted"),
  ))

  We define $phi': R[X] -> B$ by $phi'(x_s) = phi(s)^(-1)$ for all $s in S$.
  It is easy to check that $phi = phi' circle.small i$,
  since for all $r in R$,
  we have $phi(r) = r phi(1) = r 1_B$,
  and $phi' circle.small i(r) = phi'(r) = r phi'(1) = r 1_B$.

  Also $I subset.eq ker phi'$, since
  $
    phi'(s x_s-1)= phi'(s) phi'(x_s) - 1_B = h(s) h(s)^(-1) - 1_B = 0.
  $
  Thus, there exists a map $phi'': A -> B$ that makes the diagram commute.
  The map $phi''$ is unique, since if there exists $psi'$ that replace $phi'$,
  and $psi''$ that replace $phi''$ that will make the diagram commute.
  We have $psi'(s x_s - 1)=0$,
  which applies that $psi'(x_s) = phi'(x_s)$,
  and applies that $psi' = phi'$.
]

The elements in $S^(-1)R$ could be described by a queit simple form.

#proposition[
  Given a multiplicative subet $S$ of a commutative ring $R$,
  and the localization $(S^(-1)R, h)$.
  All elements in $S^(-1)R$ could be represent as $h(r)h(s)^(-1)$
  for some $r in R$, $s in S$.
]
#proof[
  Let $A = \{
    h(r)h(s)^(-1) divides r in R, s in S
  \}$ be a subset of $S^(-1)R$.
  It is easy to prove that $A$ itself is a $R$-algebra.
  Take $phi: R -> A$ be the $R$-algebra map,
  that derived by restriction of $h$.
  And easily $phi(s)$ is invertible in $A$.

  Then, we have the following commutative diagram:
  #align(center, commutative-diagram(
    node((1, 0), [$R$]),
    node((1, 1), [$A$]),
    node((0, 1), [$S^(-1)R$]),
    node((2, 1), [$S^(-1)R$]),
    arr((1, 0), (1, 1), [$phi$]),
    arr((1, 0), (0, 1), [$h$]),
    arr((1, 0), (2, 1), [$h$], label-pos: right),
    arr((0, 1), (2, 1), [$1$], curve: 30deg, label-pos: left),
    arr((0, 1), (1, 1), [$j$], label-pos: right, "dotted"),
    arr((1, 1), (2, 1), [$i$], label-pos: right, "dotted"),
  ))
  where $i$ is the inlcusion map, $1$ is the identity map,
  and $j$ is the map derived from the universal mapping property
  of the localization.
  By the universal mapping property(the uniquenice of the incudecd map),
  $j circle.small i = 1$,
  and it is easy to check the other two triangle commute,
  thus the diagram commute.
  Also, as $j circle.small i = 1$,
  by set theory, $i$ is surjective,
  thus $A = S^(-1)R$.
]

It is worthwhile to describe what element is in the kernel
of the localization map.
#proposition[
  Given a multiplicative subet $S$ of a commutative ring $R$,
  and the localization $(S^(-1)R, h)$.
  Then $
    ker h = \{
      r divides s r = 0 "for some" s in S  
    \}.
  $
]
#proof[
  Given $r in R$, s.t. $exists s in S$, $s r = 0$,
  $0 = h(s r)= h(s) h(r)$,
  and then $0 = h(s)^(-1) dot 0 = h(s)^(-1)h(s)h(r)$,
  thus $h(r) = 0$,
  thus $r in ker h$.

  Conversely, given $r in ker h$.
  As in the proof of @existence-of-localizarion-ring-map,
  $r in ker h$, if and only if $r in I$,
  where $I$ is the ideal of $R[X]$,
  generated by $\{s x_s - 1 divides s in S \}$.
  So, there exists polynomials $p_s, forall s in S$,
  that is not $0$ for only finitly many $s in S$,
  s.t. $
    r = sum_(s in S) p_s (s x_s -  1).
  $
  Take $cal(S)$ to be the set of all $s$, s.t. $p_s$ is not $0$,
  or $x_s$ appear in some non-zero $p_s$.
  It is easy to check that $cal(S)$ is finite.
  And $
    r = sum_(s in cal(S)) p_s (s x_s -  1).
  $

  Take $S'$ to be the multiplicative set generated by $cal(S)$,
  and a corresponding localization $(S'^(-1)R, h')$,
  it is clear that $r in ker h'$.
  We also define $s_0 = product_(s in cal(S))s$,
  and $S'' = \{ s_0^i divides i >= 0 \}$.
  It is clear that $S''$ is multiplicative,
  thus we define a third localization $(S''^(-1)R, h'')$.
  For all $s in cal(S)$, 
  we have $
    h''(s) h''(product_(s' in cal(S) without \{s\}) s') = h''(s_0)
  $.
  Since $h''(s_0)$ is invertible, we have $h''(s)$ invertible.
  There exists a unique $phi$ that makes the follwing diagram commute.
  #align(center, commutative-diagram(
    node((0, 0), [$R$]),
    node((0, 2), [$S'^(-1)R$]),
    node((1, 1), [$S''(-1)R$]),
    arr((0, 0), (0, 2), [$h'$]),
    arr((0, 0), (1, 1), [$h''$], label-pos: right),
    arr((0, 2), (1, 1), [$phi$], "dotted"),
  ))
  As now $h'(r) = 0$,
  we have $h''(r) = phi circle.small h' (r) = 0$,
  we have $r in ker h''$.

  Thus, there exists a polynomial $p = a_n x_(s_0)^n + dots + a_0$,
  s.t. $p (s_0 x_(s_0)  -1 )= r$.
  Then $
    s_0 a_n x_(s_0)^(n+1) + (s_0 a_(n-1) - a_(n)) x_(s_0)^(n)
    + dots
    + (s_0 a_(0) - a_(1)) x_(s_0)^(1)
    - a_0 = r.
  $
  Which directly imples:
  $s_0 a_n = 0$, $s_0 a_(n-1) = a_(n)$, $dots$, $s_0 a_(0) = a_(1)$,
  $a_0 = -r$,
  and by induction, we have $s^(n+1) r = 0$,
  which is as desired.
]
