#import "../../utils.typ": *

== Character Theory

#definition(title:[Charactor])[
  Let $V$ be a $n$-dimensional $CC$ vector space.
  Let $rho: G -> GL(V)$
  be a complex representation of $G$.
  The #highlightIndex[charactor] of
  $rho$
  is the function
  $
    chi_(rho): G -> CC, g mapsto tr (rho(g))
  $
  where $tr$ is the trace funciton.
  And the #highlightIndex[degree of the charactor]
  is just the degree of the representation.
]

We will also write $chi_V$ to denote the charactor
of the representation induced by a $CC G$-module $V$.
Note that given isomorphism of representation,
or isomorphism of $CC G$-module,
we have the same charactor.

#definition(title: [Linear Character])[
  Characters of degree $1$ are called #highlightIndex[linear character].
]

#definition(title:[Class Function])[
  A funciton $f: G -> CC$
  is said to be a #highlightIndex[class fucntion]
  if it is constant
  on conjugacy classed of $G$, i.e.
  $
    f(x g x^(-1)) = f(g), forall g, x in G.
  $

  And we denote the space of all class functions
  on $G$ by $classFunctionSpace(G)$.
]

#lemma[
  The charactor $chi_V$ of any finite dimensional $CC G$-module
  $V$ is a class funciton.
]
#proof[
  Easy check.
]

#definition(title: [Charactor Table])[
  Let $G$ be a finite group,
  let $g_1, ... , g_s$ be a set of representatives
  for the conjugacy classed of $G$
  and let $V_1, ..., V_r$
  be a complete list of non-iso simple $CC G$-modules.
  The #highlightIndex[charactor table]
  of $G$ is the $r times s$ array
  with $(i,j)$-th entry being given by $chi_(V_i) (g_j)$.
]
#remark[
  Note by @cor:numberOfSimpleMoudlesIsConjugacyClassOfGroupForKG,
  we always have $r = s$,
  so the character table is always a square.
]

Some basis simple facts about characters.
#lemma[
  Let $G$ be a finite group,
  $V$ be a $CC$ vector space.
  Let $rho: G -> GL(V)$
  be a finite dimensional representation, then:
  + $chi_V (1) = dim V$.
  + $chi_V (g) = chi_V (1)$ if and only if $rho(g) = 1$, $forall g in G$.
  + If $dim V = 1$ then $chi_V$ is a group homomorphism.
  + If $G$ is abelian and $V$ is irreducible, then $dim V = 1$.
] <lemma:simpleFactsAbourCharactors>
#proof[
  #enum(
    enum.item[
      Simple verification.
    ],
    enum.item[
      Let $n = dim V$.
      Let ${e_1, ..., e_n}$ be a complete set of eigenvalues
      of $rho(g)$.
      As $G$ is finite dimensional,
      there is $k$ s.t. $g^k = 1$.
      Then we have
      $
        e_1 + ... + e_n = n\
        e_i^k = 1, forall i
      $

      And the only solution for the above equation
      is $e_i = 1$.
      Thus $rho(g) = 1$.
    ],
    enum.item[
      If $dim V = 1$,
      then $GL (V) = CC$,
      and the trace function is just the identity funciton.
    ],
    enum.item[
      Let ${V_1,...,V_r}$ be a complete list of 
      non-iso $CC G$ simple module.
      Then by @cor:decompositionOfKGAsSimpleModuleVectorSpace,
      we have $|G| = sum_(i=1)^r (dim V_i)^2$.
      Since $G$ is abelian,
      then $|G|$ is equal to the number of the conjugacy classes
      of $G$,
      thus $|G| = r$,
      and thus $dim V_i = 1$ for each $i$.
    ]
  )
]

#proposition[
  Let $chi_1,...,chi_r$ be the complete list of characters
  of the irreducible complex representation of a finite group
  $G$.
  Then
  $
    chi_1 (1)^2 + ... + chi_r (1)^2 = |G|.
  $
]
#proof[
  Let ${V_1,...,V_r}$ be a complete list of 
  non-iso $CC G$ simple module, that correspond to
  ${chi_1,...,chi_r}$ .
  Then by @cor:decompositionOfKGAsSimpleModuleVectorSpace,
  we have $|G| = sum_(i=1)^r (dim V_i)^2$.
  And since $chi_i (1) = dim V_i$,
  by last lemma,
  we have the desired result.
]

#definition(title: [Inflated Representation])[
  Let $N$ be a normal subgroup
  of the finite group $G$
  and let $rho: G \/ N -> GL(V)$
  be a representation,
  then the #highlightIndex[inflated representation]
  of $G$:
  $
    inflatedRepresentation(rho): G -> GL (V)
  $
  is defined by $inflatedRepresentation(rho)(g) = rho(g N)$,
  $forall g in G$.
]
#definition(title: [Derived Subgorup])[
  Let $G$ be a finite group.
  The #highlightIndex[derived subgroup],
  $G'$,
  is the subgroup of $G$ generated by all
  #highlightIndex[commutator]
  $[x,y]= x y x^(-1) y^(-1)$ for $x,y in G$:
  $
    G' = chevron.l [x,y] | x,y in G chevron.r.
  $
]

#lemma[
  Let $G$ be a finite group.
  Then $G$ has precisely $|G: G'|$ distinct complex linear character.
]
#proof[
  If $G$ is abelian,
  then $|G| = |G: G'|$.
  Let $V$ be a simple $CC G$-module.
  Then by @lemma:simpleFactsAbourCharactors,
  $dim V = 1$,
  and $rho: G -> V iso CC$
  is a group homo.
  By the decomposition of finite abelian group
  into direct sums of cyclic group,
  it is easy to check that the distinct number of group homo
  $rho: G -> GL(V) iso CC$
  is $|G|$,
  thus $G$ have $|G|$ linear complex linear character.

  If $G$ is not abelian.
  Then given any linear representation $rho: G -> GL(V)$,
  we have $GL(V)$ abelian,
  thus, $rho$ factors through the abelianization of $G^"ab" = G \/ G'$,
  i.e.
  $
    G -> G^"ab" -> GL (V)
  $
  Now $G^"ab" -> GL (V)$
  is a linear representation of finite abelian group.
  Also if we are given a linear representation $G^"ab" -> GL (V)$,
  then we could define a linear representation,
  through the inflated representation.
  And thus it is easy to check that the linear representation of $G$
  is in one-one correspondence with linear representation of $G^"ab"$
  and by the first part,
  the number of distinct linear representation of $G$
  is equal to $|G^"ab"| = |G : G'|$.
]

#definition(title:"Inner Product")[
  Let $G$ be a finite group.
  The #highlightIndex[inner product on class fucntions]:
  $
    innerProduct(square, square):
    classFunctionSpace(G) times classFunctionSpace(G)
    -> CC
  $
  is defined as:
  $
    innerProduct(phi, psi): 1 /(|G|) sum_(g in G)
    overline(phi(g)) psi(g),
    forall phi, psi in classFunctionSpace(G).
  $
]
#proposition[
  The inner product on class fucntions
  have all the normal inner product properties, i.e.
  for $phi, psi in classFunctionSpace(G)$
  and $lambda in CC$:
  #enum(
    enum.item[
      $innerProduct(lambda phi, psi) =
      overline(lambda)innerProduct(phi,psi)$
      and 
      $innerProduct(phi, lambda psi) =
      lambda innerProduct(phi,psi)$.
    ],
    enum.item[
      $innerProduct(square,square)$
      is additive in both variables.
    ],
    enum.item[
      $innerProduct(phi,psi) = overline(innerProduct(psi,phi))$.
    ],
    enum.item[
      $innerProduct(phi,phi) ge 0$.
    ],
    enum.item[
      $innerProduct(phi,phi) = 0$ iff $phi = 0$.
    ]
  )
]